<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst($type) }} Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #2563eb;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .summary {
            background-color: #f3f4f6;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 15px;
        }
        .summary-item {
            text-align: center;
        }
        .summary-label {
            font-size: 10px;
            color: #666;
            text-transform: uppercase;
            margin-bottom: 5px;
        }
        .summary-value {
            font-size: 18px;
            font-weight: bold;
            color: #2563eb;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #2563eb;
            color: white;
            padding: 10px;
            text-align: left;
            font-size: 11px;
        }
        td {
            padding: 8px 10px;
            border-bottom: 1px solid #e5e7eb;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-success {
            background-color: #d1fae5;
            color: #065f46;
        }
        .badge-warning {
            background-color: #fef3c7;
            color: #92400e;
        }
        .badge-danger {
            background-color: #fee2e2;
            color: #991b1b;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ ucwords(str_replace('-', ' ', $type)) }} Report</h1>
        <p>ICT Inventory Management System</p>
        <p>Generated: {{ $generatedAt }}</p>
        @if($user)
            <p>Generated by: {{ $user->name }}</p>
        @endif
    </div>

    @if(isset($data['summary']))
        <div class="summary">
            <div class="summary-grid">
                @foreach($data['summary'] as $key => $value)
                    <div class="summary-item">
                        <div class="summary-label">{{ ucwords(str_replace('_', ' ', $key)) }}</div>
                        <div class="summary-value">
                            @if(str_contains($key, 'value') || str_contains($key, 'price'))
                                ₱{{ number_format($value, 2) }}
                            @else
                                {{ number_format($value) }}
                            @endif
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    @endif

    @if($type === 'inventory' && isset($data['assets']))
        <table>
            <thead>
                <tr>
                    <th>Asset Name</th>
                    <th>Category</th>
                    @if($isSuperAdmin)
                        <th>Department</th>
                    @endif
                    <th class="text-right">Quantity</th>
                    <th class="text-right">Available</th>
                    <th class="text-right">In Use</th>
                    <th class="text-right">Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['assets'] as $asset)
                    <tr>
                        <td>{{ $asset->name }}</td>
                        <td>{{ $asset->category->name ?? 'N/A' }}</td>
                        @if($isSuperAdmin)
                            <td>{{ $asset->department->name ?? '—' }}</td>
                        @endif
                        <td class="text-right">{{ $asset->quantity }}</td>
                        <td class="text-right">{{ $asset->quantity_available }}</td>
                        <td class="text-right">{{ $asset->quantity_in_use }}</td>
                        <td class="text-right">{{ $asset->current_value ? '₱' . number_format($asset->current_value, 2) : '—' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @if($type === 'valuation' && isset($data['assets']))
        <table>
            <thead>
                <tr>
                    <th>Asset Name</th>
                    <th>Category</th>
                    @if($isSuperAdmin)
                        <th>Department</th>
                    @endif
                    <th class="text-right">Purchase Price</th>
                    <th class="text-right">Current Value</th>
                    <th class="text-right">Depreciation</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['assets'] as $asset)
                    <tr>
                        <td>{{ $asset->name }}</td>
                        <td>{{ $asset->category->name ?? 'N/A' }}</td>
                        @if($isSuperAdmin)
                            <td>{{ $asset->department->name ?? '—' }}</td>
                        @endif
                        <td class="text-right">₱{{ number_format($asset->purchase_price ?? 0, 2) }}</td>
                        <td class="text-right">₱{{ number_format($asset->current_value ?? 0, 2) }}</td>
                        <td class="text-right">₱{{ number_format(($asset->purchase_price ?? 0) - ($asset->current_value ?? 0), 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @if($type === 'borrowings' && isset($data['borrowings']))
        <table>
            <thead>
                <tr>
                    <th>Asset</th>
                    <th>Borrower</th>
                    <th>Status</th>
                    <th>Borrowed At</th>
                    <th>Due Date</th>
                    <th>Returned At</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['borrowings'] as $borrowing)
                    <tr>
                        <td>{{ $borrowing->asset->name ?? 'N/A' }}</td>
                        <td>{{ $borrowing->user->name ?? 'N/A' }}</td>
                        <td>
                            <span class="badge 
                                @if($borrowing->status === 'returned') badge-success
                                @elseif($borrowing->status === 'overdue') badge-danger
                                @else badge-warning
                                @endif">
                                {{ ucfirst($borrowing->status) }}
                            </span>
                        </td>
                        <td>{{ $borrowing->borrowed_at ? date('M d, Y', strtotime($borrowing->borrowed_at)) : '—' }}</td>
                        <td>{{ $borrowing->due_date ? date('M d, Y', strtotime($borrowing->due_date)) : '—' }}</td>
                        <td>{{ $borrowing->returned_at ? date('M d, Y', strtotime($borrowing->returned_at)) : '—' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @if($type === 'low-stock' && isset($data['assets']))
        <table>
            <thead>
                <tr>
                    <th>Asset Name</th>
                    <th>Category</th>
                    @if($isSuperAdmin)
                        <th>Department</th>
                    @endif
                    <th class="text-right">Available</th>
                    <th class="text-right">Minimum</th>
                    <th class="text-right">Shortage</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['assets'] as $asset)
                    <tr>
                        <td>{{ $asset->name }}</td>
                        <td>{{ $asset->category->name ?? 'N/A' }}</td>
                        @if($isSuperAdmin)
                            <td>{{ $asset->department->name ?? '—' }}</td>
                        @endif
                        <td class="text-right">{{ $asset->quantity_available }}</td>
                        <td class="text-right">{{ $asset->min_quantity }}</td>
                        <td class="text-right" style="color: #dc2626; font-weight: bold;">
                            {{ $asset->min_quantity - $asset->quantity_available }}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @if($type === 'lifecycle' && (isset($data['warranty_expiring']) || isset($data['needs_retirement'])))
        @if(isset($data['warranty_expiring']) && count($data['warranty_expiring']) > 0)
            <h3 style="margin-top: 20px; color: #2563eb;">Warranty Expiring Soon (Next 30 Days)</h3>
            <table>
                <thead>
                    <tr>
                        <th>Asset Name</th>
                        <th>Category</th>
                        <th>Purchase Date</th>
                        <th>Warranty Expiry</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data['warranty_expiring'] as $asset)
                        <tr>
                            <td>{{ $asset->name }}</td>
                            <td>{{ $asset->category->name ?? 'N/A' }}</td>
                            <td>{{ $asset->purchase_date ? date('M d, Y', strtotime($asset->purchase_date)) : '—' }}</td>
                            <td>{{ $asset->warranty_expiry_date ? date('M d, Y', strtotime($asset->warranty_expiry_date)) : '—' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif

        @if(isset($data['needs_retirement']) && count($data['needs_retirement']) > 0)
            <h3 style="margin-top: 20px; color: #2563eb;">Assets Needing Retirement (Next 90 Days)</h3>
            <table>
                <thead>
                    <tr>
                        <th>Asset Name</th>
                        <th>Category</th>
                        <th>Purchase Date</th>
                        <th>Retirement Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data['needs_retirement'] as $asset)
                        <tr>
                            <td>{{ $asset->name }}</td>
                            <td>{{ $asset->category->name ?? 'N/A' }}</td>
                            <td>{{ $asset->purchase_date ? date('M d, Y', strtotime($asset->purchase_date)) : '—' }}</td>
                            <td>{{ $asset->retirement_date ? date('M d, Y', strtotime($asset->retirement_date)) : '—' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
    @endif

    @if($type === 'maintenance' && isset($data['items']))
        <table>
            <thead>
                <tr>
                    <th>Serial Number</th>
                    <th>Asset</th>
                    <th>Category</th>
                    <th>Last Maintenance</th>
                    <th>Next Maintenance</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['items'] as $item)
                    <tr>
                        <td>{{ $item->serial_number }}</td>
                        <td>{{ $item->asset->name ?? 'N/A' }}</td>
                        <td>{{ $item->asset->category->name ?? 'N/A' }}</td>
                        <td>{{ $item->last_maintenance_date ? date('M d, Y', strtotime($item->last_maintenance_date)) : '—' }}</td>
                        <td>{{ $item->next_maintenance_date ? date('M d, Y', strtotime($item->next_maintenance_date)) : '—' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        <p>This is a computer-generated report from ICT Inventory Management System</p>
        <p>© {{ date('Y') }} ICT Inventory. All rights reserved.</p>
    </div>
</body>
</html>
